/* The following code was generated by JFlex 1.7.0-SNAPSHOT tweaked for IntelliJ platform */

package org.intellij.plugins.hcl;
import com.intellij.lexer.*;
import com.intellij.psi.tree.IElementType;
import com.intellij.openapi.util.text.StringUtil;
import java.util.EnumSet;
import static org.intellij.plugins.hcl.HCLElementTypes.*;
import static com.intellij.psi.TokenType.BAD_CHARACTER;
import static com.intellij.psi.TokenType.WHITE_SPACE;

@SuppressWarnings({"ALL"})

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0-SNAPSHOT
 * from the specification file <tt>HCLLexer.flex</tt>
 */
public class _HCLLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int D_STRING = 2;
  public static final int S_STRING = 4;
  public static final int HIL_EXPRESSION = 6;
  public static final int IN_NUMBER = 8;
  public static final int S_HEREDOC_MARKER = 10;
  public static final int S_HEREDOC_LINE = 12;
  public static final int S_HEREDOC_LINE_END = 14;
  public static final int HIL_EXPRESSION_STRING = 16;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7, 
     8, 8
  };

  /** 
   * Translates characters to character classes
   * Chosen bits are [11, 6, 4]
   * Total runtime size is 13728 bytes
   */
  public static int ZZ_CMAP(int ch) {
    return ZZ_CMAP_A[(ZZ_CMAP_Y[(ZZ_CMAP_Z[ch>>10]<<6)|((ch>>4)&0x3f)]<<4)|(ch&0xf)];
  }

  /* The ZZ_CMAP_Z table has 1088 entries */
  static final char ZZ_CMAP_Z[] = zzUnpackCMap(
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7\1\10\2\11\1\12\1\13\6\14\1\15\23\14\1\16"+
    "\1\14\1\17\1\20\12\14\1\21\10\11\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1"+
    "\32\1\11\1\33\1\34\2\11\1\14\1\35\3\11\1\36\10\11\1\37\1\40\20\11\1\41\2\11"+
    "\1\42\5\11\1\43\4\11\1\44\1\45\4\11\51\14\1\46\3\14\1\47\1\50\4\14\1\51\12"+
    "\11\1\52\u0381\11");

  /* The ZZ_CMAP_Y table has 2752 entries */
  static final char ZZ_CMAP_Y[] = zzUnpackCMap(
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7\2\1\1\10\1\11\1\12\1\13\1\12\1\13\34\12\1"+
    "\14\1\15\1\16\10\1\1\17\1\20\1\12\1\21\4\12\1\22\10\12\1\23\12\12\1\24\1\12"+
    "\1\25\1\24\1\12\1\26\4\1\1\12\1\27\1\30\2\1\2\12\1\27\1\1\1\31\1\24\5\12\1"+
    "\32\1\33\1\34\1\1\1\35\1\12\1\1\1\36\5\12\1\37\1\40\1\41\1\12\1\27\1\42\1"+
    "\12\1\43\1\44\1\1\1\12\1\45\4\1\1\12\1\46\4\1\1\47\2\12\1\50\1\1\1\51\1\52"+
    "\1\24\1\53\1\54\1\55\1\56\1\57\1\60\1\52\1\15\1\61\1\54\1\55\1\62\1\1\1\63"+
    "\1\64\1\65\1\66\1\21\1\55\1\67\1\1\1\70\1\52\1\71\1\72\1\54\1\55\1\67\1\1"+
    "\1\60\1\52\1\40\1\73\1\74\1\75\1\76\1\1\1\70\1\64\1\1\1\77\1\35\1\55\1\50"+
    "\1\1\1\100\1\52\1\1\1\77\1\35\1\55\1\101\1\1\1\57\1\52\1\102\1\77\1\35\1\12"+
    "\1\103\1\57\1\104\1\52\1\105\1\106\1\107\1\12\1\110\1\111\1\1\1\64\1\1\1\24"+
    "\2\12\1\112\1\111\1\113\2\1\1\114\1\115\1\116\1\117\1\120\1\121\2\1\1\70\1"+
    "\1\1\113\1\1\1\122\1\12\1\123\1\1\1\124\7\1\2\12\1\27\1\104\1\113\1\125\1"+
    "\126\1\127\1\130\1\113\2\12\1\131\2\12\1\132\24\12\1\133\1\134\2\12\1\133"+
    "\2\12\1\135\1\136\1\13\3\12\1\136\3\12\1\27\2\1\1\12\1\1\5\12\1\137\1\24\45"+
    "\12\1\140\1\12\1\24\1\27\4\12\1\27\1\141\1\142\1\15\1\12\1\15\1\12\1\15\1"+
    "\142\1\70\3\12\1\143\1\1\1\144\1\113\2\1\1\113\5\12\1\26\2\12\1\145\4\12\1"+
    "\37\1\12\1\146\2\1\1\64\1\12\1\147\1\46\2\12\1\150\1\12\1\76\1\113\2\1\1\12"+
    "\1\111\3\12\1\46\2\1\2\113\1\151\5\1\1\106\2\12\1\143\1\152\1\113\2\1\1\153"+
    "\1\12\1\154\1\41\2\12\1\37\1\1\2\12\1\143\1\1\1\155\1\41\1\12\1\147\6\1\1"+
    "\156\1\157\14\12\4\1\21\12\1\137\2\12\1\137\1\160\1\12\1\147\3\12\1\161\1"+
    "\162\1\163\1\123\1\162\7\1\1\164\1\1\1\123\6\1\1\165\1\166\1\167\1\170\1\171"+
    "\3\1\1\172\147\1\2\12\1\146\2\12\1\146\10\12\1\173\1\174\2\12\1\131\3\12\1"+
    "\175\1\1\1\12\1\111\4\176\4\1\1\104\35\1\1\177\2\1\1\200\1\24\4\12\1\201\1"+
    "\24\4\12\1\132\1\106\1\12\1\147\1\24\4\12\1\146\1\1\1\12\1\27\3\1\1\12\40"+
    "\1\133\12\1\37\4\1\135\12\1\37\2\1\10\12\1\123\4\1\2\12\1\147\20\12\1\123"+
    "\1\12\1\202\1\1\2\12\1\146\1\104\1\12\1\147\4\12\1\37\2\1\1\203\1\204\5\12"+
    "\1\205\1\12\1\147\1\26\3\1\1\203\1\206\1\12\1\30\1\1\3\12\1\143\1\204\2\12"+
    "\1\143\1\1\1\113\1\1\1\207\1\41\1\12\1\37\1\12\1\111\1\1\1\12\1\123\1\47\2"+
    "\12\1\30\1\104\1\113\1\210\1\211\2\12\1\45\1\1\1\212\1\113\1\12\1\213\3\12"+
    "\1\214\1\215\1\216\1\27\1\65\1\217\1\220\1\176\2\12\1\132\1\37\7\12\1\30\1"+
    "\113\72\12\1\143\1\12\1\221\2\12\1\150\20\1\26\12\1\147\6\12\1\76\2\1\1\111"+
    "\1\222\1\55\1\223\1\224\6\12\1\15\1\1\1\153\25\12\1\147\1\1\4\12\1\204\2\12"+
    "\1\26\2\1\1\150\7\1\1\210\7\12\1\123\1\1\1\113\1\24\1\27\1\24\1\27\1\225\4"+
    "\12\1\146\1\226\1\227\2\1\1\230\1\12\1\13\1\231\2\147\2\1\7\12\1\27\30\1\1"+
    "\12\1\123\3\12\1\70\2\1\2\12\1\1\1\12\1\232\2\12\1\37\1\12\1\147\2\12\1\233"+
    "\3\1\11\12\1\147\1\113\5\1\2\12\1\26\3\12\1\143\11\1\23\12\1\111\1\12\1\37"+
    "\1\26\11\1\1\234\2\12\1\235\1\12\1\37\1\12\1\111\1\12\1\146\4\1\1\12\1\236"+
    "\1\12\1\37\1\12\1\76\4\1\3\12\1\237\4\1\1\70\1\240\1\12\1\143\2\1\1\12\1\123"+
    "\1\12\1\123\2\1\1\122\1\12\1\46\1\1\3\12\1\37\1\12\1\37\1\12\1\30\1\12\1\15"+
    "\6\1\4\12\1\45\3\1\3\12\1\30\3\12\1\30\60\1\1\153\2\12\1\26\2\1\1\64\1\1\1"+
    "\153\2\12\2\1\1\12\1\45\1\113\1\153\1\12\1\111\1\64\1\1\2\12\1\241\1\153\2"+
    "\12\1\30\1\242\1\243\2\1\1\12\1\21\1\150\5\1\1\244\1\245\1\45\2\12\1\146\1"+
    "\1\1\113\1\72\1\54\1\55\1\67\1\1\1\246\1\15\21\1\3\12\1\1\1\247\1\113\12\1"+
    "\2\12\1\146\2\1\1\250\2\1\3\12\1\1\1\251\1\113\2\1\2\12\1\27\1\1\1\113\3\1"+
    "\1\12\1\76\1\1\1\113\26\1\4\12\1\113\1\104\34\1\3\12\1\45\20\1\71\12\1\76"+
    "\16\1\14\12\1\143\53\1\2\12\1\146\75\1\44\12\1\111\33\1\43\12\1\45\1\12\1"+
    "\146\1\113\6\1\1\12\1\147\1\1\3\12\1\1\1\143\1\113\1\153\1\252\1\12\67\1\4"+
    "\12\1\46\1\70\3\1\1\153\6\1\1\15\77\1\6\12\1\27\1\123\1\45\1\76\66\1\5\12"+
    "\1\210\3\12\1\142\1\253\1\254\1\255\3\12\1\256\1\257\1\12\1\260\1\261\1\35"+
    "\24\12\1\262\1\12\1\35\1\132\1\12\1\132\1\12\1\210\1\12\1\210\1\146\1\12\1"+
    "\146\1\12\1\55\1\12\1\55\1\12\1\263\3\264\14\12\1\46\123\1\1\255\1\12\1\265"+
    "\1\266\1\267\1\270\1\271\1\272\1\273\1\150\1\274\1\150\24\1\55\12\1\111\2"+
    "\1\103\12\1\46\15\12\1\147\150\12\1\15\25\1\41\12\1\147\36\1");

  /* The ZZ_CMAP_A table has 3024 entries */
  static final char ZZ_CMAP_A[] = zzUnpackCMap(
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\0\1\27\1\5\1\21\2\0\1\25\2\0\1\6\1\16"+
    "\1\32\1\7\1\14\1\4\1\11\11\10\2\0\1\24\1\33\3\0\1\13\1\46\2\13\1\15\1\13\1"+
    "\45\3\20\1\45\1\20\1\45\12\20\1\12\2\20\1\30\1\26\1\31\1\0\1\20\1\0\1\41\1"+
    "\46\2\13\1\37\1\40\1\45\3\20\1\45\1\42\1\45\1\44\3\20\1\35\1\43\1\34\1\36"+
    "\2\20\1\12\2\20\1\22\1\0\1\23\14\0\1\20\12\0\1\20\4\0\1\20\5\0\27\20\1\0\12"+
    "\20\4\0\14\20\16\0\5\20\7\0\1\20\1\0\1\20\1\0\5\20\1\0\2\20\2\0\4\20\1\0\1"+
    "\20\6\0\1\20\1\0\3\20\1\0\1\20\1\0\4\20\1\0\23\20\1\0\13\20\10\0\6\20\1\0"+
    "\26\20\2\0\1\20\6\0\10\20\10\0\13\20\5\0\3\20\15\0\12\17\4\0\6\20\1\0\1\20"+
    "\17\0\2\20\7\0\2\20\12\17\3\20\2\0\2\20\1\0\16\20\15\0\11\20\13\0\1\20\16"+
    "\0\12\17\6\20\4\0\2\20\4\0\1\20\5\0\6\20\4\0\1\20\11\0\1\20\3\0\1\20\7\0\11"+
    "\20\7\0\5\20\17\0\26\20\3\0\1\20\2\0\1\20\7\0\12\20\4\0\12\17\1\20\4\0\10"+
    "\20\2\0\2\20\2\0\26\20\1\0\7\20\1\0\1\20\3\0\4\20\3\0\1\20\20\0\1\20\15\0"+
    "\2\20\1\0\1\20\5\0\6\20\4\0\2\20\1\0\2\20\1\0\2\20\1\0\2\20\17\0\4\20\1\0"+
    "\1\20\7\0\12\17\2\0\3\20\20\0\11\20\1\0\2\20\1\0\2\20\1\0\5\20\3\0\1\20\2"+
    "\0\1\20\30\0\1\20\13\0\10\20\2\0\1\20\3\0\1\20\1\0\6\20\3\0\3\20\1\0\4\20"+
    "\3\0\2\20\1\0\1\20\1\0\2\20\3\0\2\20\3\0\3\20\3\0\14\20\13\0\10\20\1\0\2\20"+
    "\10\0\3\20\5\0\4\20\1\0\5\20\3\0\1\20\3\0\2\20\15\0\13\20\2\0\1\20\21\0\1"+
    "\20\12\0\6\20\5\0\22\20\3\0\10\20\1\0\11\20\1\0\1\20\2\0\7\20\11\0\1\20\1"+
    "\0\2\20\14\0\12\17\7\0\2\20\1\0\1\20\2\0\2\20\1\0\1\20\2\0\1\20\6\0\4\20\1"+
    "\0\7\20\1\0\3\20\1\0\1\20\1\0\1\20\2\0\2\20\1\0\4\20\1\0\2\20\11\0\1\20\2"+
    "\0\5\20\1\0\1\20\11\0\12\17\2\0\14\20\1\0\24\20\13\0\5\20\3\0\6\20\4\0\4\20"+
    "\3\0\1\20\3\0\2\20\7\0\3\20\4\0\15\20\14\0\1\20\1\0\6\20\1\0\1\20\5\0\1\20"+
    "\2\0\13\20\1\0\15\20\1\0\4\20\2\0\7\20\1\0\1\20\1\0\4\20\2\0\1\20\1\0\4\20"+
    "\2\0\7\20\1\0\1\20\1\0\4\20\2\0\16\20\2\0\6\20\2\0\15\20\2\0\1\20\1\0\10\20"+
    "\7\0\15\20\1\0\6\20\23\0\1\20\4\0\1\20\3\0\11\20\1\0\1\20\5\0\17\20\1\0\16"+
    "\20\2\0\14\20\13\0\1\20\15\0\7\20\7\0\16\20\15\0\2\20\12\17\3\0\3\20\11\0"+
    "\4\20\1\0\4\20\3\0\2\20\11\0\10\20\1\0\1\20\1\0\1\20\1\0\1\20\1\0\6\20\1\0"+
    "\7\20\1\0\1\20\3\0\3\20\1\0\7\20\3\0\4\20\2\0\6\20\5\0\1\20\15\0\1\20\2\0"+
    "\1\20\4\0\1\20\2\0\12\20\1\0\1\20\3\0\5\20\6\0\1\20\1\0\1\20\1\0\1\20\1\0"+
    "\4\20\1\0\13\20\2\0\4\20\5\0\5\20\4\0\1\20\4\0\2\20\13\0\5\20\6\0\4\20\3\0"+
    "\2\20\14\0\10\20\7\0\10\20\1\0\7\20\6\0\2\20\12\0\5\20\5\0\2\20\3\0\7\20\6"+
    "\0\3\20\12\17\2\20\13\0\11\20\2\0\27\20\2\0\7\20\1\0\3\20\1\0\4\20\1\0\4\20"+
    "\2\0\6\20\3\0\1\20\1\0\1\20\2\0\5\20\1\0\12\20\12\17\5\20\1\0\3\20\1\0\10"+
    "\20\4\0\7\20\3\0\1\20\3\0\2\20\1\0\1\20\3\0\2\20\2\0\5\20\2\0\1\20\1\0\1\20"+
    "\30\0\3\20\3\0\6\20\2\0\6\20\2\0\6\20\11\0\7\20\4\0\5\20\3\0\5\20\5\0\1\20"+
    "\1\0\10\20\1\0\5\20\1\0\1\20\1\0\2\20\1\0\2\20\1\0\12\20\6\0\12\20\2\0\6\20"+
    "\2\0\6\20\2\0\6\20\2\0\3\20\3\0\14\20\1\0\16\20\1\0\2\20\1\0\2\20\1\0\10\20"+
    "\6\0\4\20\4\0\16\20\2\0\1\20\1\0\14\20\1\0\2\20\3\0\1\20\2\0\4\20\1\0\2\20"+
    "\12\0\10\20\6\0\6\20\1\0\3\20\1\0\12\20\3\0\1\20\12\0\4\20\13\0\12\17\1\20"+
    "\1\0\1\20\3\0\7\20\1\0\1\20\1\0\4\20\1\0\17\20\1\0\2\20\14\0\3\20\4\0\2\20"+
    "\1\0\1\20\20\0\4\20\10\0\1\20\13\0\10\20\5\0\3\20\2\0\1\20\2\0\2\20\2\0\4"+
    "\20\1\0\14\20\1\0\1\20\1\0\7\20\1\0\21\20\1\0\4\20\2\0\10\20\1\0\7\20\1\0"+
    "\14\20\1\0\4\20\1\0\5\20\1\0\1\20\3\0\14\20\2\0\13\20\1\0\10\20\2\0\22\17"+
    "\1\0\2\20\1\0\1\20\2\0\1\20\1\0\12\20\1\0\4\20\1\0\1\20\1\0\1\20\6\0\1\20"+
    "\4\0\1\20\1\0\1\20\1\0\1\20\1\0\3\20\1\0\2\20\1\0\1\20\2\0\1\20\1\0\1\20\1"+
    "\0\1\20\1\0\1\20\1\0\1\20\1\0\2\20\1\0\1\20\2\0\4\20\1\0\7\20\1\0\4\20\1\0"+
    "\4\20\1\0\1\20\1\0\12\20\1\0\5\20\1\0\3\20\1\0\5\20\1\0\5\20");

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\11\0\1\1\1\2\1\1\1\3\1\1\2\4\1\5"+
    "\1\4\1\6\1\7\1\1\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\3\5\1\16\2\17\3\16\2\20\2\21"+
    "\1\16\2\22\2\16\1\23\1\24\2\1\3\25\1\26"+
    "\2\27\1\26\1\30\1\31\2\32\2\33\1\16\1\34"+
    "\1\35\1\4\2\0\1\36\3\5\1\0\1\37\2\40"+
    "\2\41\1\0\1\42\2\25\2\0\2\30\1\0\2\4"+
    "\1\0\3\5\3\25\1\0\1\35\1\43\1\5\1\44"+
    "\1\45";

  private static int [] zzUnpackAction() {
    int [] result = new int[102];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\47\0\116\0\165\0\234\0\303\0\352\0\u0111"+
    "\0\u0138\0\u015f\0\u0186\0\u01ad\0\u01d4\0\u01fb\0\u0222\0\u0249"+
    "\0\u0270\0\u0297\0\u015f\0\u015f\0\u02be\0\u015f\0\u015f\0\u015f"+
    "\0\u015f\0\u015f\0\u015f\0\u02e5\0\u030c\0\u0333\0\u035a\0\u0381"+
    "\0\u015f\0\u03a8\0\u03cf\0\u015f\0\u03f6\0\u015f\0\u041d\0\u015f"+
    "\0\u0444\0\u015f\0\u03f6\0\u046b\0\u0492\0\u015f\0\u015f\0\u04b9"+
    "\0\u04e0\0\u0507\0\u052e\0\u0555\0\u015f\0\u057c\0\u015f\0\u05a3"+
    "\0\u05ca\0\u05f1\0\u0618\0\u015f\0\u063f\0\u015f\0\u0666\0\u015f"+
    "\0\u068d\0\u06b4\0\u06db\0\u0702\0\u015f\0\u0729\0\u0750\0\u0777"+
    "\0\u079e\0\u015f\0\u07c5\0\u015f\0\u07ec\0\u015f\0\u0813\0\u015f"+
    "\0\u083a\0\u0861\0\u0888\0\u08af\0\u08d6\0\u015f\0\u08fd\0\u0924"+
    "\0\u06db\0\u0924\0\u094b\0\u0972\0\u0999\0\u09c0\0\u015f\0\u09e7"+
    "\0\u0a0e\0\u015f\0\u0270\0\u0a35\0\u0270\0\u0270";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[102];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\12\3\13\1\14\1\15\1\12\1\16\1\17\1\20"+
    "\2\21\1\22\1\21\2\12\1\21\1\12\1\23\1\24"+
    "\1\25\1\26\1\12\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\3\21\1\35\3\21\1\36\2\21\1\37\1\40"+
    "\1\41\16\37\1\42\1\43\1\44\1\37\1\44\1\45"+
    "\1\46\20\37\1\47\1\50\16\37\1\42\1\51\1\44"+
    "\1\37\1\52\1\53\1\44\17\37\21\54\1\55\1\44"+
    "\1\56\1\54\1\57\1\60\1\57\17\54\7\12\1\61"+
    "\1\62\1\63\2\12\1\64\32\12\1\65\1\66\1\67"+
    "\4\65\1\70\4\71\1\65\1\71\1\65\2\71\13\65"+
    "\13\71\1\72\1\73\1\74\44\72\1\12\1\75\1\76"+
    "\44\12\21\54\1\77\2\44\1\54\1\100\1\60\1\100"+
    "\17\54\50\0\3\13\47\0\1\15\1\0\1\101\40\0"+
    "\1\15\2\0\44\15\10\0\1\17\1\20\2\0\1\22"+
    "\42\0\2\17\2\0\1\22\1\102\21\0\1\102\17\0"+
    "\2\17\1\103\1\0\1\22\1\102\21\0\1\102\16\0"+
    "\7\21\1\0\2\21\13\0\13\21\10\0\2\22\3\0"+
    "\1\104\21\0\1\104\33\0\1\105\31\0\7\21\1\0"+
    "\2\21\13\0\1\21\1\106\11\21\7\0\7\21\1\0"+
    "\2\21\13\0\5\21\1\107\5\21\7\0\7\21\1\0"+
    "\2\21\13\0\2\21\1\110\10\21\1\37\2\0\16\37"+
    "\3\0\1\37\1\0\1\111\1\0\17\37\2\0\1\41"+
    "\66\0\1\112\25\0\1\113\1\114\44\0\1\37\2\0"+
    "\23\37\1\44\20\37\2\0\1\50\45\0\1\115\1\116"+
    "\44\0\21\54\3\0\1\54\1\0\1\117\1\0\17\54"+
    "\22\0\1\120\24\0\1\54\2\0\22\54\1\44\1\54"+
    "\1\44\17\54\10\0\1\62\1\63\2\0\1\64\42\0"+
    "\2\62\2\0\1\64\1\121\21\0\1\121\5\0\1\122"+
    "\11\0\2\62\1\123\1\0\1\64\1\121\21\0\1\121"+
    "\5\0\1\122\11\0\2\64\3\0\1\124\21\0\1\124"+
    "\5\0\1\122\3\0\1\67\54\0\4\71\1\0\1\71"+
    "\1\0\2\71\13\0\13\71\1\0\1\125\1\126\5\0"+
    "\4\71\1\0\1\71\1\0\2\71\13\0\13\71\1\72"+
    "\2\0\44\72\2\0\1\74\46\0\1\76\66\0\1\44"+
    "\24\0\6\101\1\127\40\101\7\0\3\130\4\0\1\130"+
    "\40\0\2\131\1\0\1\131\1\0\1\131\21\0\3\131"+
    "\4\0\1\131\7\0\1\132\2\130\4\0\1\132\37\0"+
    "\7\21\1\0\2\21\13\0\2\21\1\133\10\21\7\0"+
    "\7\21\1\0\2\21\13\0\6\21\1\134\4\21\7\0"+
    "\7\21\1\0\2\21\13\0\6\21\1\135\4\21\1\37"+
    "\2\0\23\37\1\0\20\37\2\0\1\114\46\0\1\116"+
    "\44\0\1\54\2\0\22\54\1\0\1\54\1\0\17\54"+
    "\7\0\3\136\4\0\1\136\26\0\1\122\47\0\1\137"+
    "\10\0\2\140\1\0\1\140\1\0\1\140\21\0\3\140"+
    "\4\0\1\140\7\0\1\141\2\136\4\0\1\141\32\0"+
    "\1\126\44\0\4\101\1\142\42\101\10\0\2\130\44\0"+
    "\7\21\1\0\2\21\13\0\3\21\1\143\7\21\7\0"+
    "\7\21\1\0\2\21\13\0\7\21\1\144\3\21\7\0"+
    "\7\21\1\0\2\21\13\0\6\21\1\145\4\21\10\0"+
    "\2\136\33\0\1\122\11\0\2\140\1\0\1\140\1\0"+
    "\1\140\21\0\3\140\3\0\1\122\1\140\10\0\2\136"+
    "\44\0\7\21\1\0\2\21\13\0\3\21\1\146\7\21";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2652];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\11\0\1\11\10\1\2\11\1\1\6\11\5\1\1\11"+
    "\2\1\1\11\1\1\1\11\1\1\1\11\1\1\1\11"+
    "\3\1\2\11\5\1\1\11\1\1\1\11\4\1\1\11"+
    "\1\1\1\11\1\1\1\11\2\1\2\0\1\11\3\1"+
    "\1\0\1\11\1\1\1\11\1\1\1\11\1\0\1\11"+
    "\2\1\2\0\1\1\1\11\1\0\2\1\1\0\4\1"+
    "\1\11\1\1\1\0\1\11\4\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[102];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  // This parameters can be getted from capabilities
    private boolean withNumbersWithBytesPostfix;
    private boolean withInterpolationLanguage;

    public _HCLLexer(EnumSet<HCLCapability> capabilities) {
      this((java.io.Reader)null);
      this.withNumbersWithBytesPostfix = capabilities.contains(HCLCapability.NUMBERS_WITH_BYTES_POSTFIX);
      this.withInterpolationLanguage = capabilities.contains(HCLCapability.INTERPOLATION_LANGUAGE);
    }
    enum StringType {
      None, SingleQ, DoubleQ
    }
  // State data
    StringType stringType = StringType.None;
    int stringStart = -1;
    int hil = 0;
    int myHereDocMarkerLength = 0;
    int myHereDocMarkerWeakHash = 0;
    boolean myHereDocIndented = false;
    char myILStringChar;

    private void hil_inc() {
      hil++;
    }
    private int hil_dec() {
      assert hil > 0;
      hil--;
      return hil;
    }
    private void push_eol() {
      yypushback(getEOLLength());
    }
    private int getEOLLength() {
      if (yylength() == 0) return 0;
      char last = yycharat(yylength() - 1);
      if (last != '\r' && last != '\n') return 0;
      if ((yylength() > 1) && yycharat(yylength() - 2) == '\r') return 2;
      return 1;
    }
    private IElementType eods() {
      yybegin(YYINITIAL); stringType = StringType.None; zzStartRead = stringStart; return DOUBLE_QUOTED_STRING;
    }
    private IElementType eoss() {
      yybegin(YYINITIAL); stringType = StringType.None; zzStartRead = stringStart; return SINGLE_QUOTED_STRING;
    }
    private IElementType eoil() {
      hil=0; return stringType == StringType.SingleQ ? eoss(): eods();
    }
    private void setHereDocMarker(CharSequence marker) {
      myHereDocIndented = true; // Temprorarly set to true see #30
      int length = marker.length();
      String value = marker.toString();
      assert(length > 0);
      if (marker.charAt(0) == '-') {
        assert(length > 1);
        // Indented heredoc
        myHereDocIndented = true;
        length--;
        value = value.substring(1);
      }
      myHereDocMarkerLength = length & 0xFF;
      int hash = value.hashCode();
      myHereDocMarkerWeakHash = hash & 0xFFFF;
    }
    private void resetHereDocMarker() {
      myHereDocMarkerLength = 0;
      myHereDocMarkerWeakHash = 0;
    }
    private boolean isHereDocMarkerDefined() {
      return myHereDocMarkerLength != 0 && myHereDocMarkerWeakHash != 0;
    }
    private boolean isHereDocMarker(CharSequence input) {
      if (myHereDocIndented) input = StringUtil.trimLeading(input);
      if ((input.length() & 0xFF) != myHereDocMarkerLength) return false;
      int hash = input.toString().hashCode();
      return myHereDocMarkerWeakHash == (hash & 0xFFFF);
    }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public _HCLLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    int size = 0;
    for (int i = 0, length = packed.length(); i < length; i += 2) {
      size += packed.charAt(i);
    }
    char[] map = new char[size];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < packed.length()) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + ZZ_CMAP(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        switch (zzLexicalState) {
            case D_STRING: {
              return eods();
            }
            case 103: break;
            case S_STRING: {
              return eoss();
            }
            case 104: break;
            case HIL_EXPRESSION: {
              return eoil();
            }
            case 105: break;
            case S_HEREDOC_MARKER: {
              yybegin(YYINITIAL); return BAD_CHARACTER;
            }
            case 106: break;
            case S_HEREDOC_LINE: {
              yybegin(YYINITIAL); return BAD_CHARACTER;
            }
            case 107: break;
            case S_HEREDOC_LINE_END: {
              yybegin(YYINITIAL); return BAD_CHARACTER;
            }
            case 108: break;
            case HIL_EXPRESSION_STRING: {
              return eoil();
            }
            case 109: break;
            default:
        return null;
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return BAD_CHARACTER;
            }
          case 38: break;
          case 2: 
            { return WHITE_SPACE;
            }
          case 39: break;
          case 3: 
            { return LINE_COMMENT;
            }
          case 40: break;
          case 4: 
            { if (!withNumbersWithBytesPostfix) return NUMBER;
                                yybegin(IN_NUMBER); yypushback(yylength());
            }
          case 41: break;
          case 5: 
            { return ID;
            }
          case 42: break;
          case 6: 
            { return L_CURLY;
            }
          case 43: break;
          case 7: 
            { return R_CURLY;
            }
          case 44: break;
          case 8: 
            { stringType = StringType.SingleQ; stringStart = zzStartRead; yybegin(S_STRING);
            }
          case 45: break;
          case 9: 
            { stringType = StringType.DoubleQ; stringStart = zzStartRead; yybegin(D_STRING);
            }
          case 46: break;
          case 10: 
            { return L_BRACKET;
            }
          case 47: break;
          case 11: 
            { return R_BRACKET;
            }
          case 48: break;
          case 12: 
            { return COMMA;
            }
          case 49: break;
          case 13: 
            { return EQUALS;
            }
          case 50: break;
          case 14: 
            { 
            }
          case 51: break;
          case 15: 
            { push_eol(); return eods();
            }
          case 52: break;
          case 16: 
            { return eods();
            }
          case 53: break;
          case 17: 
            { push_eol(); return eoss();
            }
          case 54: break;
          case 18: 
            { return eoss();
            }
          case 55: break;
          case 19: 
            { if (hil_dec() <= 0) yybegin(stringType == StringType.SingleQ ? S_STRING: D_STRING);
            }
          case 56: break;
          case 20: 
            { myILStringChar=yycharat(yylength() - 1); yybegin(HIL_EXPRESSION_STRING);
            }
          case 57: break;
          case 21: 
            { yybegin(YYINITIAL); return NUMBER;
            }
          case 58: break;
          case 22: 
            { if (!isHereDocMarkerDefined()) {
      yybegin(YYINITIAL);
      return BAD_CHARACTER;
    }
    yybegin(S_HEREDOC_LINE);
    return BAD_CHARACTER;
            }
          case 59: break;
          case 23: 
            { if (!isHereDocMarkerDefined()) {
      yybegin(YYINITIAL);
      return BAD_CHARACTER;
    }
    yybegin(S_HEREDOC_LINE);
    return WHITE_SPACE;
            }
          case 60: break;
          case 24: 
            { yypushback(getEOLLength());
    setHereDocMarker(yytext());
    return HD_MARKER;
            }
          case 61: break;
          case 25: 
            { int eol = getEOLLength();
    int len = yylength();
    int len_eff = len - eol;
    assert len_eff >= 0;
    if((len_eff & 0xFF) >= myHereDocMarkerLength
       && isHereDocMarker(yytext().subSequence(0, len_eff))) {
      // End of HereDoc
      yypushback(eol);
      yybegin(YYINITIAL);
      resetHereDocMarker();
      return HD_MARKER;
    } else {
      yybegin(S_HEREDOC_LINE_END);
      return HD_LINE;
    }
            }
          case 62: break;
          case 26: 
            { yypushback(getEOLLength()); yybegin(S_HEREDOC_LINE_END); return HD_LINE;
            }
          case 63: break;
          case 27: 
            { yybegin(S_HEREDOC_LINE); return HD_EOL;
            }
          case 64: break;
          case 28: 
            { if(myILStringChar == yycharat(yylength() - 1)) {yybegin(HIL_EXPRESSION);}
            }
          case 65: break;
          case 29: 
            { return BLOCK_COMMENT;
            }
          case 66: break;
          case 30: 
            { yybegin(S_HEREDOC_MARKER); return HD_START;
            }
          case 67: break;
          case 31: 
            { if (withInterpolationLanguage) {hil_inc(); yybegin(HIL_EXPRESSION);}
            }
          case 68: break;
          case 32: 
            { push_eol(); yypushback(1); return eods();
            }
          case 69: break;
          case 33: 
            { push_eol(); yypushback(1); return eoss();
            }
          case 70: break;
          case 34: 
            { hil_inc();
            }
          case 71: break;
          case 35: 
            { return TRUE;
            }
          case 72: break;
          case 36: 
            { return NULL;
            }
          case 73: break;
          case 37: 
            { return FALSE;
            }
          case 74: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
