/* The following code was generated by JFlex 1.7.0-SNAPSHOT tweaked for IntelliJ platform */

package org.intellij.plugins.hil.psi;

import com.intellij.lexer.*;
import com.intellij.psi.tree.IElementType;
import static org.intellij.plugins.hil.HILElementTypes.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0-SNAPSHOT
 * from the specification file <tt>_HILLexer.flex</tt>
 */
public class _HILLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\2\2\1\1\2\22\0\1\1\1\30\1\3\1\0"+
    "\1\16\1\27\1\34\1\0\1\21\1\22\1\14\1\12\1\25\1\15"+
    "\1\10\1\26\1\5\11\7\1\36\1\0\1\32\1\31\1\33\1\37"+
    "\1\0\4\13\1\11\25\13\1\23\1\4\1\24\1\0\1\13\1\0"+
    "\1\45\3\13\1\43\1\44\5\13\1\46\1\13\1\50\3\13\1\41"+
    "\1\47\1\40\1\42\2\13\1\6\2\13\1\17\1\35\1\20\7\0"+
    "\1\1\32\0\1\1\u15df\0\1\1\u097f\0\13\1\35\0\2\1\5\0"+
    "\1\1\57\0\1\1\u0fa0\0\1\1\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\ud00f\0";

  /** 
   * Translates characters to character classes
   */
  private static final int ZZ_SX = 0x0700;
  private static final int ZZ_MX = 0x10000;
  private static final int ZZ_LX = 0x110000;
  private static char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED, ZZ_SX);
  private static class M { static final char [] MAP = zzUnpackCMap(ZZ_CMAP_PACKED, ZZ_MX); }
  private static class L { static final char [] MAP = zzUnpackCMap(ZZ_CMAP_PACKED, ZZ_LX); }

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\4\1\6"+
    "\1\7\1\10\1\11\1\1\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\1\1\23\1\24"+
    "\2\1\1\25\1\26\3\5\1\3\4\0\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\3\5\2\4\1\0"+
    "\3\5\1\36\1\5\1\37\1\40";

  private static int [] zzUnpackAction() {
    int [] result = new int[56];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\51\0\51\0\122\0\173\0\244\0\315\0\51"+
    "\0\51\0\51\0\51\0\366\0\51\0\51\0\51\0\51"+
    "\0\51\0\51\0\51\0\51\0\u011f\0\u0148\0\u0171\0\u019a"+
    "\0\u01c3\0\u01ec\0\51\0\51\0\u0215\0\u023e\0\u0267\0\51"+
    "\0\u0290\0\u02b9\0\u02e2\0\u030b\0\51\0\51\0\51\0\51"+
    "\0\51\0\51\0\51\0\u0334\0\u035d\0\u0386\0\u03af\0\u03d8"+
    "\0\u03d8\0\u0401\0\u042a\0\u0453\0\244\0\u047c\0\244\0\244";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[56];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\2\1\5\1\6\1\7\1\10"+
    "\1\6\1\11\1\6\1\12\1\13\1\14\1\2\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\3\6\1\36\3\6\1\37\51\0\2\4\1\0\1\40"+
    "\1\41\44\4\5\0\1\7\1\42\1\7\1\43\1\44"+
    "\31\0\1\44\12\0\3\6\1\0\1\6\1\0\3\6"+
    "\22\0\11\6\5\0\1\7\1\0\1\7\1\43\1\44"+
    "\31\0\1\44\24\0\1\45\62\0\1\46\50\0\1\47"+
    "\50\0\1\50\50\0\1\51\53\0\1\52\51\0\1\53"+
    "\20\0\3\6\1\0\1\6\1\0\3\6\22\0\1\6"+
    "\1\54\7\6\5\0\3\6\1\0\1\6\1\0\3\6"+
    "\22\0\5\6\1\55\3\6\5\0\3\6\1\0\1\6"+
    "\1\0\3\6\22\0\2\6\1\56\6\6\2\4\1\0"+
    "\46\4\5\0\1\7\1\0\1\7\46\0\1\57\1\0"+
    "\1\57\46\0\1\60\1\0\1\60\2\0\1\61\2\0"+
    "\1\61\40\0\3\6\1\0\1\6\1\0\3\6\22\0"+
    "\2\6\1\62\6\6\5\0\3\6\1\0\1\6\1\0"+
    "\3\6\22\0\6\6\1\63\2\6\5\0\3\6\1\0"+
    "\1\6\1\0\3\6\22\0\6\6\1\64\2\6\5\0"+
    "\1\57\1\0\1\57\1\0\1\44\31\0\1\44\12\0"+
    "\1\60\1\0\1\60\46\0\3\6\1\0\1\6\1\0"+
    "\3\6\22\0\3\6\1\65\5\6\5\0\3\6\1\0"+
    "\1\6\1\0\3\6\22\0\7\6\1\66\1\6\5\0"+
    "\3\6\1\0\1\6\1\0\3\6\22\0\6\6\1\67"+
    "\2\6\5\0\3\6\1\0\1\6\1\0\3\6\22\0"+
    "\3\6\1\70\5\6";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1189];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\4\1\4\11\1\1\10\11\6\1\2\11"+
    "\3\1\1\11\4\0\7\11\5\1\1\0\7\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[56];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  public _HILLexer() {
    this((java.io.Reader)null);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public _HILLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed, int limit) {
    char [] map = new char[limit];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 184 && j < limit) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0 && j < limit);
    }
    return map;
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          if (zzInput >= zzCMapL.length) ZZ_CMAP = zzCMapL = zzInput >= ZZ_MX ? L.MAP : M.MAP;
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return com.intellij.psi.TokenType.BAD_CHARACTER;
            }
          case 33: break;
          case 2: 
            { return com.intellij.psi.TokenType.WHITE_SPACE;
            }
          case 34: break;
          case 3: 
            { return DOUBLE_QUOTED_STRING;
            }
          case 35: break;
          case 4: 
            { return NUMBER;
            }
          case 36: break;
          case 5: 
            { return ID;
            }
          case 37: break;
          case 6: 
            { return OP_DOT;
            }
          case 38: break;
          case 7: 
            { return OP_PLUS;
            }
          case 39: break;
          case 8: 
            { return OP_MUL;
            }
          case 40: break;
          case 9: 
            { return OP_MINUS;
            }
          case 41: break;
          case 10: 
            { return INTERPOLATION_END;
            }
          case 42: break;
          case 11: 
            { return L_PAREN;
            }
          case 43: break;
          case 12: 
            { return R_PAREN;
            }
          case 44: break;
          case 13: 
            { return L_BRACKET;
            }
          case 45: break;
          case 14: 
            { return R_BRACKET;
            }
          case 46: break;
          case 15: 
            { return COMMA;
            }
          case 47: break;
          case 16: 
            { return OP_DIV;
            }
          case 48: break;
          case 17: 
            { return OP_MOD;
            }
          case 49: break;
          case 18: 
            { return OP_NOT;
            }
          case 50: break;
          case 19: 
            { return OP_LESS;
            }
          case 51: break;
          case 20: 
            { return OP_GREATER;
            }
          case 52: break;
          case 21: 
            { return OP_COLON;
            }
          case 53: break;
          case 22: 
            { return OP_QUEST;
            }
          case 54: break;
          case 23: 
            { return INTERPOLATION_START;
            }
          case 55: break;
          case 24: 
            { return OP_NOT_EQUAL;
            }
          case 56: break;
          case 25: 
            { return OP_EQUAL;
            }
          case 57: break;
          case 26: 
            { return OP_LESS_OR_EQUAL;
            }
          case 58: break;
          case 27: 
            { return OP_GREATER_OR_EQUAL;
            }
          case 59: break;
          case 28: 
            { return OP_AND_AND;
            }
          case 60: break;
          case 29: 
            { return OP_OR_OR;
            }
          case 61: break;
          case 30: 
            { return TRUE;
            }
          case 62: break;
          case 31: 
            { return NULL;
            }
          case 63: break;
          case 32: 
            { return FALSE;
            }
          case 64: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
