// From https://github.com/hashicorp/hcl/blob/master/hcl/parse.y

{
  tokens = [
    space = "regexp:\s+"
    line_comment = "regexp:(//.*)|(#.*)"
    block_comment = "regexp:/\*(.|\n)*\*/"

    t_string = "regexp:\"[^\"]*\""
    t_id = "regexp:[a-zA-Z\._]+"
    t_boolean = "regexp:(true)|(false)"

    t_integer = "regexp:-?\d+([eE][-+]?\d+)?"
    t_float = "regexp:-?\d+(\.\d+)?([eE][-+]?\d+)?"

  ]
}



top::= objectlist?

objectlist::=objectitem+

object::='{' objectlist? '}'

objectkey::=t_id | t_string

objectitem::=objectkey '=' (number | t_boolean | t_string | object | list)
            | block

block::=blockId+ object

blockId::=t_id | t_string

list::='[' listitems? ']'

listitems::=listitem (',' listitem)? ','?

listitem::=number | t_string

number::= t_integer | t_float